import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { SidebarProvider } from "@/components/ui/sidebar";
import { PropertySidebar } from "@/components/PropertySidebar";
import { AppHeader } from "@/components/AppHeader";
import { Plus, Calendar, Users, Building } from "lucide-react";
import { format } from "date-fns";

interface BidData {
  id: string;
  generatedBy: string;
  email: string;
  phone: string;
  companyName: string;
  property: any;
  startDate: Date;
  endDate: Date;
  scopeType: string;
  jobCategories: any[];
  contractors: any[];
  createdAt: string;
}

export default function BidsList() {
  const navigate = useNavigate();
  const [bids, setBids] = useState<BidData[]>([]);

  useEffect(() => {
    // Load bids from localStorage
    const savedBids = JSON.parse(localStorage.getItem('propertyBids') || '[]');
    setBids(savedBids);
  }, []);

  const handleBidClick = (bidId: string) => {
    navigate(`/property/bid/${bidId}`);
  };

  const handleCreateNewBid = () => {
    navigate('/property/bids');
  };

  const getBidStatus = (bid: BidData) => {
    const now = new Date();
    const startDate = bid.startDate ? new Date(bid.startDate) : null;
    const endDate = bid.endDate ? new Date(bid.endDate) : null;
    
    if (!startDate || !endDate || isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
      return "Unknown";
    }
    
    if (now < startDate) return "Pending";
    if (now >= startDate && now <= endDate) return "Active";
    return "Completed";
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "Pending": return "bg-yellow-100 text-yellow-800";
      case "Active": return "bg-green-100 text-green-800";
      case "Completed": return "bg-gray-100 text-gray-800";
      case "Unknown": return "bg-red-100 text-red-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  const formatBidDate = (date: Date | string | undefined): string => {
    if (!date) return "Not set";
    const dateObj = new Date(date);
    if (isNaN(dateObj.getTime())) return "Invalid date";
    return format(dateObj, 'MMM dd, yyyy');
  };

  return (
    <SidebarProvider>
      <div className="min-h-screen flex w-full bg-background">
        <PropertySidebar />
        <div className="flex-1 flex flex-col">
          <AppHeader />
          <main className="flex-1 p-6 space-y-6">
            <div className="flex justify-between items-center">
              <div>
                <h1 className="text-3xl font-bold text-foreground">Renovation Bids</h1>
                <p className="text-muted-foreground mt-1">
                  Manage and track your property bids
                </p>
              </div>
              <Button 
                onClick={handleCreateNewBid}
                className="flex items-center gap-2"
              >
                <Plus className="h-4 w-4" />
                Create New Bid
              </Button>
            </div>

            {bids.length === 0 ? (
              <Card className="p-12 text-center">
                <div className="mx-auto w-16 h-16 bg-muted rounded-full flex items-center justify-center mb-4">
                  <Building className="h-8 w-8 text-muted-foreground" />
                </div>
                <h3 className="text-lg font-semibold mb-2">No bids created yet</h3>
                <p className="text-muted-foreground mb-4">
                  Get started by creating your first renovation bid
                </p>
                <Button onClick={handleCreateNewBid}>
                  <Plus className="h-4 w-4 mr-2" />
                  Create Your First Bid
                </Button>
              </Card>
            ) : (
              <div className="grid gap-6">
                {bids.map((bid) => (
                  <Card 
                    key={bid.id} 
                    className="hover:shadow-md transition-shadow cursor-pointer"
                    onClick={() => handleBidClick(bid.id)}
                  >
                    <CardHeader>
                      <div className="flex justify-between items-start">
                        <div>
                          <CardTitle className="text-xl">Bid #{bid.id}</CardTitle>
                          <p className="text-muted-foreground">
                            Generated by {bid.generatedBy} • {bid.companyName}
                          </p>
                        </div>
                        <Badge className={getStatusColor(getBidStatus(bid))}>
                          {getBidStatus(bid)}
                        </Badge>
                      </div>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div className="flex items-center gap-2">
                          <Calendar className="h-4 w-4 text-muted-foreground" />
                          <div>
                            <p className="text-sm font-medium">Start Date</p>
                            <p className="text-sm text-muted-foreground">
                              {formatBidDate(bid.startDate)}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Calendar className="h-4 w-4 text-muted-foreground" />
                          <div>
                            <p className="text-sm font-medium">End Date</p>
                            <p className="text-sm text-muted-foreground">
                              {formatBidDate(bid.endDate)}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Users className="h-4 w-4 text-muted-foreground" />
                          <div>
                            <p className="text-sm font-medium">Contractors</p>
                            <p className="text-sm text-muted-foreground">
                              {bid.contractors.length} selected
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Building className="h-4 w-4 text-muted-foreground" />
                          <div>
                            <p className="text-sm font-medium">Scope</p>
                            <p className="text-sm text-muted-foreground">
                              {bid.scopeType}
                            </p>
                          </div>
                        </div>
                      </div>
                      
                      {bid.jobCategories.length > 0 && (
                        <div>
                          <p className="text-sm font-medium mb-2">Job Categories</p>
                          <div className="flex flex-wrap gap-2">
                            {bid.jobCategories.map((category, index) => (
                              <Badge key={index} variant="secondary">
                                {category.name}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </main>
        </div>
      </div>
    </SidebarProvider>
  );
}